### ISSUE TITLE
Errors from inline code blocks

### ISSUE THREAD

**Issue by LowlyDBA** [GeopJr/action-accessibility#29]
Love the tool! 

I noticed some repeated failures on a comment I left that had an inline code block: 

```
/bin/sh: 2: Syntax error: word unexpected (expecting ")")

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12) {
  killed: false,
  code: 2,
  signal: null,
  cmd: `espeak -v en-uk-north -w tts.wav "Issue Comment: For the asset piece of the puzzle, I've found (yet another) no-config bot that might work well - AccessLint which checks for alt text and other areas that are key for accessibility in HTML.\n` +
    'Example of it working on one of my repos here.\n' +
    'Likewise, I was thinking of a PR to add the quick-and-dirty accessibility widget (adjusts contracts, fonts, CSS, etc.) that could take some of the initial burden off designing the site perfectly accessible from the start - but was unsure how the current pages are being generated and if adding the below manually to them would be a problematic integration point:\n' +
    '`js\n' +
    '    (function(d){\n' +
    '         var s = d.createElement("script");\n' +
    '         /* uncomment the following line to override default position*/\n' +
    '         /* s.setAttribute("data-position", 3);*/\n' +
    '         /* uncomment the following line to override default size (values: small, large)*/\n' +
    '         /* s.setAttribute("data-size", "small");*/\n' +
    '         /* uncomment the following line to override default language (e.g., fr, de, es, he, nl, etc.)*/\n' +
    '         /* s.setAttribute("data-language", "language");*/\n' +
    '         /* uncomment the following line to override color set via widget (e.g., #053f67)*/\n' +
    '         /* s.setAttribute("data-color", "#053e67");*/\n' +
    '         /* uncomment the following line to override type set via widget (1=person, 2=chair, 3=eye, 4=text)*/\n' +
    '         /* s.setAttribute("data-type", "1");*/\n' +
    '         /* s.setAttribute("data-statement_text:", "Our Accessibility Statement");*/\n' +
    '         /* s.setAttribute("data-statement_url", "http://www.example.com/accessibility")";*/\n' +
    '         /* uncomment the following line to override support on mobile devices*/\n' +
    '         /* s.setAttribute("data-mobile", true);*/\n' +
    '         /* uncomment the following line to set custom trigger action for accessibility menu*/\n' +
    '         /* s.setAttribute("data-trigger", "triggerId")*/\n' +
    '         s.setAttribute("src", "https://cdn.userway.org/widget.js");\n' +
    '         (d.body || d.head).appendChild(s);\n' +
    '    })\n' +
    '    (document);\n' +
    '`\n' +
    'Again, example of it on my site here (bottom right)."'
}
Error: ENOENT: no such file or directory, open './tts.wav'
```

https://github.com/sqlcollaborative/DataSaturdays/runs/1601117853?check_suite_focus=true

**Comment by GeopJr** [comment]
Thanks for the report!

The action was made during a hackathon and most of the code was rashed.
I'll work on rewriting or at least cleaning everything up and use the above use case to make sure it passes!

**Comment by GeopJr** [comment]
This ([amongst others](https://github.com/GeopJr/action-accessibility/releases/tag/v2.0.0)) got partially fixed. Follow up issue on the markdown stripper is #31.

Closing.
Thanks for the report!
